### ISSUE TITLE
docx file is too large，can't find end of central directory: is this a zip file

### ISSUE THREAD

**Issue by just5even** [VolodymyrBaydalka/docxjs#100]
When the docx file is too large, such as a file with 19MB or over 1000 pages, the issue of 'jszip: can't find end of central directory: is this a zip file' will appear
![image](https://github.com/VolodymyrBaydalka/docxjs/assets/39088410/8c0bbdbf-a7a3-4a79-9652-1bdf72d4ff88)

**Comment by Gateway-aitools** [comment]
Getting this same issue.
Is there any solution?

**Comment by avichovatiya67** [comment]
https://github.com/VolodymyrBaydalka/docxjs/issues/100

**Comment by VolodymyrBaydalka** [comment]
Tested with document on 1232 pages - works fine. Tested with 32mb document - works fine. Most likely your documents are corrupted.

**Comment by avichovatiya67** [comment]
@VolodymyrBaydalka 
Can you share the example code?

**Comment by millet0328** [comment]
> When the docx file is too large, such as a file with 19MB or over 1000 pages, the issue of 'jszip: can't find end of central directory: is this a zip file' will appear ![image](https://private-user-images.githubusercontent.com/39088410/312802676-8c0bbdbf-a7a3-4a79-9652-1bdf72d4ff88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTE1MjMsIm5iZiI6MTcxMTk1MTIyMywicGF0aCI6Ii8zOTA4ODQxMC8zMTI4MDI2NzYtOGMwYmJkYmYtYTdhMy00YTc5LTk2NTItMWJkZjcyZDRmZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTZiYTc1ZjA0MGZjZDc4MTE1ZGFmNGU0MGZjNDMwNGIzMjMwYzAxZjVlMjk4MGQ5ODBjNWYwZGFhMjFiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UjG2j7kFc1oarPC5qjPVY9RvrfP2C-DxeXkWv1sKJU)

you should upload your file to test
