### ISSUE TITLE
render document style error, Transparent shapes will be rendered black by plugin

### ISSUE THREAD

**Issue by wangermaizi** [VolodymyrBaydalka/docxjs#103]
Transparent shapes in a word document are rendered black in the page, eg:
this is origin file
![image](https://github.com/VolodymyrBaydalka/docxjs/assets/55691571/e8f06c58-dd52-40c1-9b75-bb8ddc9f40dd)

and on the websize is
![image](https://github.com/VolodymyrBaydalka/docxjs/assets/55691571/d5af4339-b1cc-4b4c-bd47-a14c95e66cb1)

[1.铸销加工会议问题.docx](https://github.com/VolodymyrBaydalka/docxjs/files/14680925/1.docx)

**Comment by VolodymyrBaydalka** [comment]
Would recommend you to add next style to your application, to fix this issue

```css
.docx svg {
    fill: transparent;
}
```

**Comment by VolodymyrBaydalka** [comment]
Partially fixed in 0.3.1
