### ISSUE TITLE
SIMPLE FIX - "praseAsync" should be renamed to "parseAsync"

### ISSUE THREAD

**Issue by kwils1997** [VolodymyrBaydalka/docxjs#105]
Pretty sure this is a typo.  Just fix the spelling with a global search & replace.

-------

FYI - "prase" is defined as:
"A chalcedony that is translucent and yellowish green."

FYI - "chalcedony" is defined as:
"A microcrystalline type of quartz occurring in several different forms, including onyx, agate, and jasper."

In other words, it's a type of rock or crystal.

**Comment by VolodymyrBaydalka** [comment]
Fixed in 0.3.1
