### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by QastanFIT** [VolodymyrBaydalka/docxjs#106]
**Describe the bug**
The library itself works perfect, for me. However, when running the React app there are a couple of warnings in the console.

**Expected behavior**
Having no warnings and/or errors in console

WARNING in ./node_modules/docx-preview/dist/docx-preview.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '\node_modules\docx-preview\src\word-document.ts' file: Error: ENOENT: no such file or directory, open '\node_modules\docx-preview\src\word-document.ts'

**Comment by zhangluka** [comment]
i'm also ,   so how do u fix this bug  ?

**Comment by zhangluka** [comment]
https://github.com/facebook/create-react-app/pull/11752   hope can help u
