### ISSUE TITLE
Retrieve image files and hyperlinks.(parseAsyn)

### ISSUE THREAD

**Issue by refuse-c** [VolodymyrBaydalka/docxjs#107]
**Describe the bug**
How can I retrieve image files and hyperlink URLs from the result of parsing a Word document using parseAsyn

**Document**
If applicable, add *.docx document to help explain your problem.
[test.docx](https://github.com/VolodymyrBaydalka/docxjs/files/14965048/test.docx)

**Expected behavior**

**Screenshots**
![PixPin_2024-04-13_10-51-33](https://github.com/VolodymyrBaydalka/docxjs/assets/38646454/204ee301-e5f0-448f-905a-e0a9f36767f0)

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser chrome
 - Version  123

**Additional context**

**Comment by VolodymyrBaydalka** [comment]
Depends on document links could be inserted as application instructions. Images - just a file of docx package (could be opened with any .zip). This library doesn't provide public API to work or modify document and it's not recommended to use it for anything else then rendering.
