### ISSUE TITLE
[BugReport]Can not show file preview correctly on mobile(simulation)

### ISSUE THREAD

**Issue by CoderMonkie** [VolodymyrBaydalka/docxjs#109]
**Describe the bug**
version: 0.3.0
using official demo
turn to dev mode by F12，and use mobile mode

**Document**

**Expected behavior**

**Screenshots**
![image](https://github.com/VolodymyrBaydalka/docxjs/assets/26118847/e0beeb1d-0e1f-4aa9-8242-bf2892589169)

**Desktop (please complete the following information):**
 - OS: Desktop(windows11)/mobile(android,iOS)
 - Browser chrome
 - Version 0.3.0

**Additional context**

**Comment by millet0328** [comment]
> **Describe the bug** version: 0.3.0 using official demo turn to dev mode by F12，and use mobile mode
> 
> **Document**
> 
> **Expected behavior**
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/26118847/323169575-e0beeb1d-0e1f-4aa9-8242-bf2892589169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTc2NDMsIm5iZiI6MTcxNDA5NzM0MywicGF0aCI6Ii8yNjExODg0Ny8zMjMxNjk1NzUtZTBiZWViMWQtMGUxZi00YWE5LTgyNDItYmYyODkyNTg5MTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAyMDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmUzYzViZDU5Mjk3ZTU3M2ZjMWVlOTdlZWFkMWE3MTUzOGJiNzkyOWRlN2Y3YmZlNzQ1YTczZjI2ZDE3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jh83NM0J1sd2w-MQ84QlTRIQuclQGDs2CWtm1RmND7Q)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Desktop(windows11)/mobile(android,iOS)
> * Browser chrome
> * Version 0.3.0
> 
> **Additional context**

文档本身是A4纸或者A5纸大小，本身已经限定宽高了，怎么可能在手机端显示？
The document itself is A4 paper or A5 paper size, itself has been limited width and height, how can display on the phone?

**Comment by VolodymyrBaydalka** [comment]
@CoderMonkie .docx provides exact physical size of document. If you want to resize/scale document to fit mobile, it's out of scope of this library and it's task for your as developer to implement that in your application depends of your requirments.
