### ISSUE TITLE
TypeError: can't access property "id", e is null

### ISSUE THREAD

**Issue by def00111** [VolodymyrBaydalka/docxjs#112]
**Describe the bug**
Can't open the document.

**Document**
[Attachment D - Instructions.docx](https://github.com/VolodymyrBaydalka/docxjs/files/15171925/Attachment.D.-.Instructions.docx)

**Expected behavior**
It should render the document.

**Screenshots**
![firefox_gc1id4oBKZ](https://github.com/VolodymyrBaydalka/docxjs/assets/10849366/ae046053-4cb4-4f4f-b6bd-da0b27744dc9)

**Desktop (please complete the following information):**
 - OS: Windows_NT 10.0 22631
 - Browser Firefox Nightly
 - Version 127.0a1 (2024-04-30) (32-Bit)

**Additional context**
I'm calling docx.renderAsync with the following options:
```
await docx.renderAsync(blob, container, null, {
      inWrapper: false,
      ignoreWidth: true,
      ignoreHeight: true,
      ignoreLastRenderedPageBreak: false,
      experimental: false,
      renderChanges: true,
      renderComments: true
    });
```

**Comment by VolodymyrBaydalka** [comment]
Fixed in 0.3.1
