### ISSUE TITLE
Crashes in Opera

### ISSUE THREAD

**Issue by Amerlander** [VolodymyrBaydalka/docxjs#121]
In Opera the whole page crashes without any error in the console output.

I tried disabling all extensions and also used inkognito session, but it still failes. The same documents are rendering fine in other chromium based browsers like vivaldi, edge and chrome.

It happenes with many files, I was not able to tackle it down exactly. But it might have something to do with relative to the page positioned elements in the document.

**Document**
[test.docx](https://github.com/user-attachments/files/15847482/test.2.docx)

**Expected behavior**
Not crashing.

**Screenshots**
![image](https://github.com/VolodymyrBaydalka/docxjs/assets/3764089/e47a2d9d-9b7a-4931-b46e-76b9d73de5ec)

Translation from the screenshot:

*Page crashed*
Unfortunately, the page could no longer be displayed. The reason could be, for example, a conflict between extensions.
Try reloading the page, or visit another page to continue.
[Reload the page]

**Desktop:**
OS: Windows 11 64-bit
Opera One(Version: 110.0.5130.82)
Update-Stream:Stable
Chromium-Version:124.0.6367.243

**Comment by VolodymyrBaydalka** [comment]
Works fine  with Opera One (112.0.5197.30)
![image](https://github.com/user-attachments/assets/bfbd5ae5-111b-45b9-9b18-cf2f8e75ec24)


P.S. now I have Opera installed on my PC 😒
