### ISSUE TITLE
How do I generate navigation labels

### ISSUE THREAD

**Issue by hangjob** [VolodymyrBaydalka/docxjs#27]
我想把 标题 生成导航标签，类似以下这样

I want the title to generate a navigation tag, something like this

![image](https://user-images.githubusercontent.com/22078920/149457505-80d66708-d4fe-4956-bbae-c67992a8c35b.png)

**Comment by hangjob** [comment]
What are the solutions

**Comment by zVolodymyr** [comment]
Since table of contents is built using the TOC fields, there is no easy way to get table of contents. Partial solution is to select all elements headers styles/classes.

**Comment by VolodymyrBaydalka** [comment]
Closed as duplication of #4
