### ISSUE TITLE
Document serial number is missing.

### ISSUE THREAD

**Issue by clayton8011** [VolodymyrBaydalka/docxjs#31]
For Chinese documents, the serial number is seriously lost, both Chinese and digital. Line breaks are also not accurate enough, and there are some problems with consistency.

**Comment by zVolodymyr** [comment]
What is "serial number"?

P.S. When you create issues please provide example documents and explain expected result (screens would be nice).

**Comment by leeguooooo** [comment]
[document.docx](https://github.com/VolodymyrBaydalka/docxjs/files/9524645/document.docx)
