### ISSUE TITLE
Can't read the data of 'the loaded zip file'

### ISSUE THREAD

**Issue by w19871029** [VolodymyrBaydalka/docxjs#41]
**Describe the bug**
Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc)

**Document**
`axios({
        method: 'get',
        responseType: 'blob',
        url: '***'
      }).then(({ data }) => {
        console.log('测试数据', docx)
        docx.renderAsync(data, document.getElementById('documentDocx'), null, {
          renderHeaders: false,
          renderFooters: false,
          debug: true
        }).then(x => {
          console.log(x)
        })
      });`

**Comment by weiyan-zzh** [comment]
How to solve this problem like this？

**Comment by w19871029** [comment]
打印返回结果 Blob 参数 type: application/vnd.openxmlformats-officedocument.wordprocessingml.document，这个才是标准的docx格式，其他应该会报错

**Comment by initiald20** [comment]
> 打印返回结果 Blob 参数 type: application/vnd.openxmlformats-officedocument.wordprocessingml.document，这个才是标准的docx格式，其他应该会报错

这个type应该前端改还是后端改
