### ISSUE TITLE
How to show revisions in word docx

### ISSUE THREAD

**Issue by eggangel** [VolodymyrBaydalka/docxjs#44]
**Describe the bug**
Can't show revisions in docx preview. 

**Document**
The file can't show revisions is uploaded below.
[test.docx](https://github.com/VolodymyrBaydalka/docxjs/files/9298616/test.docx)

**Expected behavior**
Hope to show revisions on website.

**Screenshots**
![image](https://user-images.githubusercontent.com/17508100/183863803-55761665-9427-4886-b598-d45b850fb426.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [all]

**Comment by leeguooooo** [comment]
m

**Comment by leeguooooo** [comment]
I have fixed this problem，submitting PR.

**Comment by leeguooooo** [comment]
https://github.com/VolodymyrBaydalka/docxjs/pull/46

**Comment by VolodymyrBaydalka** [comment]
Should be fixed in version 0.1.12
