### ISSUE TITLE
firefox 50 bug

### ISSUE THREAD

**Issue by basonwoo** [VolodymyrBaydalka/docxjs#45]
using `const` in loop would cause a problem in firefox 50
```
SyntaxError: missing = in const declaration
```

[https://stackoverflow.com/questions/39044803/syntaxerror-missing-in-const-declaration-firefox-50](https://stackoverflow.com/questions/39044803/syntaxerror-missing-in-const-declaration-firefox-50)

**Comment by VolodymyrBaydalka** [comment]
I'm afraid I will not downgrade code to support outdated browsers. I recommend you to build your version by setting build target to es5.
