### ISSUE TITLE
"inWrapper" not check,  serial number error .

### ISSUE THREAD

**Issue by leeguooooo** [VolodymyrBaydalka/docxjs#48]
## inWrapper:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/9278645/189541732-c8be15b1-8319-41fe-9fc7-18291910b1eb.png">

##not inWrapper:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/9278645/189541773-01f27af3-d279-4e42-8724-ea5d6903acfc.png">

## file:

[问题排查流程.docx](https://github.com/VolodymyrBaydalka/docxjs/files/9543193/default.docx)

**Comment by VolodymyrBaydalka** [comment]
Fixed in version 0.1.13

**Comment by fat-rab** [comment]
this problem stilll have
