### ISSUE TITLE
Can't find end of central directory

### ISSUE THREAD

**Issue by userxxj** [VolodymyrBaydalka/docxjs#52]
jszip.min.js?2e68:13 Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at h.readEndOfCentral (jszip.min.js?2e68:13:1)
    at h.load (jszip.min.js?2e68:13:1)
    at eval (jszip.min.js?2e68:13:1)

The docx file used can be opened normally and is not damaged

**Comment by ammad172** [comment]
I am also facing this issue seems like it's not opening when given binary of docx file

**Comment by VolodymyrBaydalka** [comment]
*.docx file is a package based on ZIP. In other words if you can't unzip you file with any zip tool - it's no .docx file, but something else.

**Comment by ammad172** [comment]
> 

Can you guide me with a code snippet how can preview base64 of a docx file using your tool?

**Comment by VolodymyrBaydalka** [comment]
@ammad172 - `docx.renderAsync(atob(docBase64), document.getElementById("container"))`.

**Comment by ammad172** [comment]
> @ammad172 - `docx.renderAsync(atob(docBase64), document.getElementById("container"))`.

Thank you i will try it as soon as possible and tell if it succeeded.
