### ISSUE TITLE
document is not defined when using on React

### ISSUE THREAD

**Issue by thegiantgod** [VolodymyrBaydalka/docxjs#56]
I am trying to use this library in a React app, but everytime I try to use renderAsync(), an error appears telling me "document is not defined".

Here is my code. I am using TypeScript on a next.js project.

import styles from '../styles/Home.module.css'
import { renderAsync, defaultOptions } from 'docx-preview'
import React, { useEffect, useRef, useState } from "react";
import DocViewer, {PDFRenderer} from 'react-doc-viewer';
import JSZip from 'jszip';

export default function Home() {

  const [text, setText] = useState("Docx document reader");
  const [file, setFile] = useState();
  const [show, setShow] = useState(false);

  const onChange = (e: any) => {
    if (e !== null) {
      setText("File uploaded !");
      setFile(e)
    }
  };

  const previewFile = () => {
    if (file !== null) {
      
      setShow(true);

      if (typeof document !== "undefined") {
        // document exists
        let container = document.getElementById("preview") as HTMLElement;
        console.log(container)
        //Render the Word Document.
        renderAsync(file, container);
      } 
      else {
        // document does not exist
      }
  
    }
  }
  

  return (
    <div className={styles.container}>
      <p>{text}</p>

      <input type="file" accept='.docx' value={file} onChange={e => onChange(e.target.value)}/>
      <input type="button" id="btnPreview" value="Preview Word Document" onClick={previewFile} />

      <div id='preview' ></div>
      {/*(show && file !== undefined) && <DocViewer pluginRenderers={[PDFRenderer]} documents={[{uri: require('C:/Users/LudovicBORGES/Documents/wrd-reader/word.txt')}]}/>*/}

    </div>
  )
}

**Comment by VolodymyrBaydalka** [comment]
If you're trying to render document using server-side rendering - it will not work

**Comment by Armito** [comment]
same problem and I solve it with using import() to dynamically load.

**Comment by jpresagios** [comment]
@thegiantgod  I'm using SSR, the way that I found is dynaically loading the library on useEffect, it's the way to go as mention @Armito 

useEffect(() => {
    const { renderAsync } = await import("docx-preview");
  }, []);
