### ISSUE TITLE
upload .docx file to demo, has error: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by En777** [VolodymyrBaydalka/docxjs#58]
**Describe the bug**
docx cannot render,
TypeError: Cannot read properties of null (reading 'headerRefs')
    at HtmlRenderer.renderSections           (html-renderer.ts:315:64)
    at HtmlRenderer.render                        (html-renderer.ts:118:30)
    at docx-preview.ts:57:22

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [107.0.5304.63]

**Comment by En777** [comment]
I fix it at my fork , maybe it not best
https://github.com/En777/docxjs-word-preview/commit/9eed2dbb212de225c60dd619c69cb4ea70377780

and npm package
https://www.npmjs.com/package/docx-preview-lib

**Comment by En777** [comment]
error: Cannot read properties of null (reading 'headerRefs') footerRefs  is also fixed.

**Comment by VolodymyrBaydalka** [comment]
should be fixed in 0.1.15
