### ISSUE TITLE
There is an exception in the latest version of Google Chrome

### ISSUE THREAD

**Issue by userxgl** [VolodymyrBaydalka/docxjs#67]
Error: This page contains the following errors:error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

**Comment by dodoliu** [comment]
i had the same problem

**Comment by JokeShaco** [comment]
i had the same problem

**Comment by rookieDJ** [comment]
i had the same problem

**Comment by Venvivo** [comment]
i had the same problem

**Comment by Venvivo** [comment]
how to fix it?

**Comment by zyp0910** [comment]
我有同样的问题

**Comment by VolodymyrBaydalka** [comment]
Please provide details about issue - document example, OS, exact browser version 

P.S. Please use issue template in future, it was added for a reason

**Comment by Venvivo** [comment]
os : win10 1809
browser version ： Chrome  114.0.5735.110
document example：see appendix

**Comment by Venvivo** [comment]
> Please provide details about issue - document example, OS, exact browser version
> 
> P.S. Please use issue template in future, it was added for a reason

os : win10 1809
browser version ： Chrome 114.0.5735.110
document example：see appendix
[日本的半导体制造装置的出口规定自身反弹.docx](https://github.com/VolodymyrBaydalka/docxjs/files/11729880/default.docx)

**Comment by LllliuA** [comment]
I had the same issue. 
I'd like to preview .doc file, so I send the .doc file to backend, backend convert .doc to .docx stream then frontend gets the response and then use the renderAsync function to display, but hit the same issue.
OS: windows 11
browser: google V114.0.5735.134
tip: it was working fine for google's version 113.xxx

**Comment by Yacj** [comment]
Same problem Same file Local preview is fine If it's a url file This page contains the following errors:error on line 1 at column 1: Document is empty Low versions of chrome do not report this error.

**Comment by VolodymyrBaydalka** [comment]
Since lack of details I assume that issue was on client side (in other words you trying to pass invalid file into function). Closing it.
