### ISSUE TITLE
Pain points on interop with docx.js

### ISSUE THREAD

**Issue by Downchuck** [VolodymyrBaydalka/docxjs#79]
I hit two points of a little extra work with docx.js and unrelated, zip.js:

There is a name collision on the docx global name - which would be fine if this library just added methods to that global docx if it exists, but it currently wipes it out. The other item is that the jszip dependency could be better documented, so that if it exists or if it's just being supported through another library, the surface of what that API needs to look like would help.

**Comment by VolodymyrBaydalka** [comment]
Package type changed to module and use **mjs** by default. This should help.
