### ISSUE TITLE
[BUG] - Multi page docx is rendered as single page html

### ISSUE THREAD

**Issue by sujit-baniya** [VolodymyrBaydalka/docxjs#89]
**Describe the bug**
The docx file with no page break (continuous multiple pages) is rendered as single page html in preview

**Document**
If applicable, add *.docx document to help explain your problem.

**Expected behavior**
Page break is expected with header and footer as in the document

**Additional context**
[Sample.zip](https://github.com/VolodymyrBaydalka/docxjs/files/13472496/Sample.zip)

**Comment by VolodymyrBaydalka** [comment]
Duplicate of #39
