### ISSUE TITLE
When innerHtml container, image doesnt has src value

### ISSUE THREAD

**Issue by irsyaadbp** [VolodymyrBaydalka/docxjs#92]
**Describe the bug**
I want get html content from result render with container.innerHtml
but when i get the content with innerHtml image tag doesnt has src value
you can see with this codesandbox
https://codesandbox.io/p/devbox/interesting-shamir-qljqwm?file=%2Fsrc%2FApp.vue%3A1,25

**Expected behavior**
Image tag has src value

**Comment by VolodymyrBaydalka** [comment]
Fixed in master and will be published with next version
