### ISSUE TITLE
remote file's ab cannot be turn into WordDocument?

### ISSUE THREAD

**Issue by brady-man-847** [VolodymyrBaydalka/docxjs#93]
**Describe the bug**

Hello.
I'm developing docx viewer on my service.
I tested in storybook, and It works very well even if mammoth.js eventually css.

but I found that viewer can view only local files. :(

it there anyway to open docx files in remote server ?

because of JSZip loadAsync error ?

please help :)
Just let me know even if I can do or not.

thanks 👍  

**Document**
If applicable, add *.docx document to help explain your problem.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by VolodymyrBaydalka** [comment]
1. Issues not for questions
2. `renderAsync` accepts `Blob` and code like `fetch('http://domain.com/path/to/my/document').then(resp => resp.blob()).then(blob => renderAsync(blob, documentContainer, styleConteiner)` is basic for web developers
