### ISSUE TITLE
Numbering Styling Missing

### ISSUE THREAD

**Issue by sandy-yeseul** [VolodymyrBaydalka/docxjs#96]
**Describe the bug**
Numbering stylings are missing and it does not display numbering correctly

**Expected behavior**
Numbering is broken, so I checked the code and it doesn't have correct css class with them.

Either need the class naming to be correct on styling sheet or html code side

**Screenshots**
<img width="789" alt="image" src="https://github.com/VolodymyrBaydalka/docxjs/assets/49422051/99067e16-016e-4d0c-97fe-578add044c5b">
<img width="481" alt="image" src="https://github.com/VolodymyrBaydalka/docxjs/assets/49422051/b88ea2df-133f-4b21-8bfe-5880e171f5ce">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by VolodymyrBaydalka** [comment]
Would recommend to add sample of document.

**Comment by VolodymyrBaydalka** [comment]
No example document is provided,  closing.
